services:
  pokenjmin-bot:
    image: miitos/pokenjmin-bot:latest
    container_name: pokenjmin-bot
    restart: unless-stopped
    volumes:
      - /volume1/docker/PokenjminBot/Data:/usr/src/app/Data
      - /volume1/docker/PokenjminBot/settings.json:/usr/src/app/settings.json
      - /volume1/docker/PokenjminBot/Exports:/usr/src/app/Exports
    deploy:
      resources:
        limits:
          cpus: 1.5
          memory: 1G
          pids: 200