import json
from photoshop import Session
import photoshop.api as photoshop
import os
from tempfile import mkdtemp
import sys
import time
from pypdf import PdfWriter

#This script takes a json generated by the bot using export_all and turns it into full cards
settingsFile= open('settings.json', encoding="utf-8")
settings=json.load(settingsFile)

#region Photoshop management
#Get layer by path written as Group/Group/Layer, for exampel Infos/Name
def get_layer_by_path(ps, layerPath):
    subGroups=str(layerPath).split("/")
    if(len(subGroups)<=1):
        return ps.active_document.artLayers.getByName(layerPath)
    
    i=0
    layerGroup=ps.active_document
    while(i<len(subGroups)-1):
        layerGroup= layerGroup.layerSets.getByName(subGroups[i])
        i+=1

    return layerGroup.artLayers.getByName(subGroups[len(subGroups)-1])

#https://loonghao.github.io/photoshop-python-api/examples/#replace-images
def replace_image(ps, layerToReplace, input_file):
    active_layer = layerToReplace
    ps.active_document.activeLayer=active_layer
    bounds = active_layer.bounds
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, input_file)
    ps.app.executeAction(replace_contents, desc)

    # replaced image.
    current_bounds = active_layer.bounds
    width = bounds[2] - bounds[0]
    height = bounds[3] - bounds[1]

    current_width = current_bounds[2] - current_bounds[0]
    current_height = current_bounds[3] - current_bounds[1]
    sizeMultiplier=width / current_width   
    newHeight=sizeMultiplier*current_height
    if(newHeight<height):
        sizeMultiplier=height/current_height

    new_size = sizeMultiplier * 100
    active_layer.resize(new_size, new_size, ps.AnchorPosition.MiddleCenter)

#https://graphicdesign.stackexchange.com/a/165157
def ptToPx(pt:float):
    return (settings["PreviewDPI"]/72) * pt

def pxToPt(px:float):
    return (72/settings["PreviewDPI"]) * px

#Very close to bot.py's create_svg_card 
def create_psd_card(cardDatas, cohort, spe, fileName, cardImagesName, isPreview=False):
    with Session(os.path.join(os.getcwd(),settings["TemplatePsdFile"]), action="open", auto_close=True) as ps:
        i=0

        previewWatermark=ps.active_document.layerSets.getByName(settings["PreviewLayerGroup"])
        previewWatermark.visible=isPreview
        
        ownerNameLayer = get_layer_by_path(ps,settings["OwnerNameLayer"])
        ownerNameLayer.textItem.contents = cardDatas["owner_name"]

        cardNameLayer = get_layer_by_path(ps,settings["CardNameLayer"])
        cardNameLayer.textItem.contents = cardDatas["card_name"]
        if(cardDatas["card_name_font_size"]!=None):
            fontSize=pxToPt(float(cardDatas["card_name_font_size"]))
            cardNameLayer.textItem.size=fontSize
        cardNameLayer.textItem.contents = cardDatas["card_name"]

        descriptionLayer = get_layer_by_path(ps,settings["DescriptionLayer"])
        descriptionLayer.textItem.contents = cardDatas["card_description"]

        cpNameLayer = get_layer_by_path(ps,settings["CPNameLayer"])
        cpNameLayer.textItem.contents = str(cardDatas["cp_name"]).upper()

        cpValueLayer = get_layer_by_path(ps,settings["CPValueLayer"])
        cpValueLayer.textItem.contents = str(cardDatas["cp_value"])

        bottomTextLayer = get_layer_by_path(ps,settings["BottomTextLayer"])
        bottomTextLayer.textItem.contents = "["+cardDatas["bottom_text_title"]+"] "+cardDatas["bottom_text_content"]

        cardImagePath=os.path.join(os.getcwd(),settings["CardImagesFolder"],cardImagesName)
        if os.path.exists(cardImagePath):
            cardImageLayer=get_layer_by_path(ps,settings["CardImageLayer"])
            replace_image(ps,cardImageLayer,cardImagePath)

        ownerPhotoPath=os.path.join(os.getcwd(),settings["OwnerPhotosFolder"],cardImagesName)
        if os.path.exists(ownerPhotoPath):
            ownerPhotoLayer=get_layer_by_path(ps,settings["OwnerPhotoLayer"])
            replace_image(ps,ownerPhotoLayer,ownerPhotoPath)

        skill1Datas=cardDatas["skill1"]
        skill1LayerSet=ps.active_document.layerSets.getByName(settings["Skill1Group"])
        fill_layers_for_skill(ps,skill1LayerSet,skill1Datas)

        skill2Datas=cardDatas["skill2"]
        skill2LayerSet=ps.active_document.layerSets.getByName(settings["Skill2Group"])
        fill_layers_for_skill(ps,skill2LayerSet,skill2Datas)

        if(spe==None): spe=0

        speIconLayerGroup=ps.active_document.layerSets.getByName(settings["SpeIconGroupName"])
        set_spe_image(speIconLayerGroup,spe,"IconLayerName")

        backgroundLayerGroup=ps.active_document.layerSets.getByName(settings["BackgroundsGroupName"])
        set_spe_image(backgroundLayerGroup, spe,"BackgroundLayerName")

        watermarkLayerGroup=ps.active_document.layerSets.getByName(settings["WatermarkGroupName"])
        set_spe_image(watermarkLayerGroup, spe,"WatermarkLayerName")

        cohortNameLayer = get_layer_by_path(ps,settings["CohortNameValueLayer"])
        cohortNameLayer.textItem.contents = cohort

        if isPreview:
            option = ps.JPEGSaveOptions()
            option.quality=1
            #you can't change the "jpg" part of the export path (for jpeg for example), Photoshop would overwrite it
            jpegPath = os.path.join(mkdtemp(),str(fileName)+".jpg")
            ps.active_document.saveAs(jpegPath, option)
            return jpegPath

        #export the pdf
        option = ps.PDFSaveOptions()
        option.jpegQuality = 12
        option.layers = False
        option.view = False  # opens the saved PDF in Acrobat.
        pdf = os.path.join(os.getcwd(),settings["ExportPdfFolder"],fileName+".pdf")
        ps.active_document.saveAs(pdf, option)
        return pdf

def fill_layers_for_skill(ps, skillLayerGroup, skillDatas):
    skillDescLayer=skillLayerGroup.artLayers.getByName(settings["SkillDescLayerName"])
    skillDescLayer.textItem.contents=skillDatas["skill_desc"]
    skillTitleLayer=skillLayerGroup.artLayers.getByName(settings["SkillTitleLayerName"])
    skillTitleLayer.textItem.contents=skillDatas["skill_name"]
    skillCostLayer=skillLayerGroup.artLayers.getByName(settings["SkillCostLayerName"])
    skillCost=skillDatas["skill_cost"]
    if(skillCost<-9999999):
        skillCost=""
    skillCostLayer.textItem.contents=str(skillCost)

    spe1IconGroup=skillLayerGroup.layerSets.getByName(settings["Spe1IconGroupName"])
    set_spe_image(spe1IconGroup,skillDatas["spe1"],"IconLayerName")

    spe2IconGroup=skillLayerGroup.layerSets.getByName(settings["Spe2IconGroupName"])
    set_spe_image(spe2IconGroup,skillDatas["spe2"],"IconLayerName")

    spe3IconGroup=skillLayerGroup.layerSets.getByName(settings["Spe3IconGroupName"])
    set_spe_image(spe3IconGroup,skillDatas["spe3"],"IconLayerName")

    return

def set_spe_image(speIconsGroup, speId, imageLayerKey):
    chosenSpe=None
    for spe in settings["Specialties"]:
        if spe["Id"]==speId:
            chosenSpe=spe
            break
    
    if(chosenSpe==None):
        speIconsGroup.visible=False
        return

    for iconLayer in speIconsGroup.artLayers:
        iconLayer.visible=iconLayer.name==chosenSpe[imageLayerKey]
#endregion

if(len(sys.argv)<2):
    print("/!\\ You need to pass a json with card datas as input, generate it with the command /export_all on the bot")
    exit(0)

inputPath=sys.argv[1]
if(inputPath==None):
    print("/!\\ You need to pass a json with card datas as input, generate it with the command /export_all on the bot")
    exit(0)
if(os.path.exists(inputPath)==False):
    print("/!\\ Path to json doesnt exist")
    exit(0)

with open(inputPath, encoding='utf-8') as fh:
    users = json.load(fh)

i=0
nbrOfUsers=len(users)
merger = PdfWriter()
for user in users:
    i+=1
    card=user["card"]
    print("Card "+str(i)+"/"+str(nbrOfUsers)+" - Owner:"+card["owner_name"]+" - Card name:"+card["card_name"])
    start=time.perf_counter()
    pngImagesName=str(user["discord_id"])+".png"
    fileName=(str(user["cohort"])+"-"+str(user["spe"])+"-"+str(i)+card["owner_name"])+".generated"
    merger.append(create_psd_card(card,user["cohort"],user["spe"],fileName,pngImagesName,False))
    end=time.perf_counter()
    print("\tFinished in "+str(end-start)+"s")

merger.write(os.path.join(settings["ExportPdfFolder"],"0-FullDeck.generated.pdf"))
merger.close