import json
from photoshop import Session
import photoshop.api as photoshop
import os
from tempfile import mkdtemp
import sys
import time
import re
import xml.etree.ElementTree as ET
from pypdf import PdfWriter
from io import BytesIO
import shutil
from PIL import Image

#This script takes a json generated by the bot using export_all and turns it into full cards
settingsFile= open('settings.json', encoding="utf-8")
settings=json.load(settingsFile)

#temp directory aren't liked by photoshop, so we save it in the working directory, in a temp folder ignored by git
tempFolder=os.path.join(os.getcwd(),"temp")
if(os.path.exists(tempFolder)): shutil.rmtree(tempFolder)
if(os.path.exists(tempFolder)==False): os.mkdir(tempFolder)

#Taken straight from bot.py, do not change code of functions here, change it in bot.py then copy paste it here
#region SVG management

def change_font_size_of_svg_layer(layer,sizeInPx:float, fontScaleRatio, psdToSvgCoordinatesMultiplier):
    textDiv=None
    for child in layer:
        if sanitizeTag(child.tag)=="text":
            textDiv=child
            break
    if(textDiv==None):
        print("/!\\Couldn't find a text layer for  "+layer.attrib['id'])

    style=textDiv.attrib["style"]
    oldFontSize=getFontSizeFromStyle(style)
    newFontSize=fontScaleRatio*sizeInPx
    textDiv.attrib["style"]=getStyleWithNewFontSize(style, newFontSize)
    #It makes the text "centered" on its resize, only works for horizontal texts, if in the future you want scalable vertical text, you'll have to change things here
    translate_node(textDiv, 0, 0.5*(oldFontSize-newFontSize))


def translate_node(node, deltaX,deltaY, relativeToScale:bool=True):
    #First we get and store the transform attribute
    
    if("transform" not in node.attrib): 
        transform="translate(0 0)"
    else:
        transform=node.attrib["transform"]

    if(transform=="" or transform==None):
        transform="translate(0 0)"

    # Extraire les valeurs de translation
    translatePattern = r'translate\(([^)]+)\)'
    translateMatch = re.search(translatePattern, transform)

    scale_pattern = r'scale\(([^)]+)\)'
    scale_match = re.search(scale_pattern, transform)
    scaleFactor=1
    if scale_match and relativeToScale:
        #sometime the scale is sliglty different on x and y, leading to 2 value, but we can afford to not care
        scaleFactor = float(scale_match.group(1).split(" ")[0])
    
    values = translateMatch.group(1).split(" ")
    x = float(values[0])
    y = float(values[1]) if len(values) > 1 else 0.0
    x += scaleFactor*deltaX
    y += scaleFactor*deltaY

    newTransformString=transform.replace(f"translate({translateMatch.group(1)})",f"translate({x} {y})")
    node.attrib["transform"]=newTransformString

#Get layer by path written as Group/Group/Layer, for exampel Infos/Name
def get_svg_layer_by_path(root, layerPath):
    subGroups=str(layerPath).split("/")
    currentLayer=root
    if(" " in layerPath or "_" in layerPath):
        print("/!\\ Error: layerPath:"+layerPath+" contains a forbidden character: \" \" or a \"_\"")

    for group in subGroups:
        nextLayer=None
        if(currentLayer==None):continue
        for child in currentLayer:
            if sanitizeTag(child.tag)!="g":continue
            #If the g node has no id, it's probably a mask, so we just replace it with its "true" layer child
            if('id' not in child.attrib): 
                gChild=child[0]
                if(gChild==None): continue
                if(sanitizeTag(gChild.tag)!="g"):continue
                if('id' not in gChild.attrib):continue
                child=gChild
            #If there's a child data-name we can try it too for more accuracy
            if isSvgLayerEqual(child.attrib['id'],group) or ("data-name" in child.attrib and child.attrib["data-name"]==group):
                nextLayer=child
                break
        if(nextLayer==None):
            print("/!\\Couldn't find the layer "+layerPath)
        currentLayer=nextLayer
    return currentLayer

def getFontSizeFromStyle(style:str):
    pattern = r"font-size:\s*([\d.]+)px"
    match = re.search(pattern, style)
    fontSize=float(match.group(1))
    return fontSize

#Returns the new style
def getStyleWithNewFontSize(style:str, newFontSize:float):
    pattern=r"(font-size:[ ]*.*px;*)"
    match=re.search(pattern, style)
    style=style.replace(match.group(1),'')
    if style=="":
        style="font-size: "+str(newFontSize)+"px"
    else:
        style=style+";"+"font-size: "+str(newFontSize)+"px"
    return style
    
def get_text_node_of_svg_layer(layer):
    for child in layer:
        if sanitizeTag(child.tag)=="text":
            textDiv=child
            break
    if(textDiv==None):
        print("/!\\Couldn't find a text layer for  "+layer.attrib['id'])
    return textDiv

def change_text_of_svg_layer(layer,text:str):
    text=str(text)
    textDiv=None
    for child in layer:
        if sanitizeTag(child.tag)=="text":
            textDiv=child
            break
    if(textDiv==None):
        print("/!\\Couldn't find a text layer for  "+layer.attrib['id'])

    textDiv.text=text

def toggle_svg_layer_visibility(layer, visibility:bool):
    notVisibleString="display:none;"
    visibleString="display:inline;"

    desiredString=notVisibleString
    undesiredString=visibleString
    if(visibility):
        desiredString=visibleString
        undesiredString=notVisibleString

    if("style" not in layer.attrib):
        layer.attrib["style"]=desiredString
        return

    if(undesiredString in layer.attrib["style"]):
        layer.attrib["style"]=layer.attrib["style"].replace(undesiredString, desiredString)
        return
    
    if(desiredString in layer.attrib["style"]):
        return
    
    layer.attrib["style"]=desiredString+layer.attrib["style"]


#node.find doesn't work because the tags are prefixed with bullshit, so we made our own version
def find_child_by_sanitize_tag(node, tag):
    for child in node:
        if(sanitizeTag(child.tag)==tag):
            return child
    return None
    
#The tags are all prefixed by "{http://www.w3.org/2000/svg}", this function removes it
def sanitizeTag(input:str):
    return input.replace("{http://www.w3.org/2000/svg}","")

#Remove everything after a "_" in a layer id, keeping only the good part. But yes, it means we can't have "_" in the actual name of the id
def sanitizeLayerId(input:str):
    return input.split("_")[0]

#since we mess with underscores and layer IDs in the SVG are suffixed with weird numbers, we can't just do ==, and yes, this raise the problem of false positivie, but it's an issue for a future programmer :)
def isSvgLayerEqual(svgLayerId:str, target:str):
    if(" " in target or "_" in target):
        print("/!\\ Error: layerPath:"+target+" contains a forbidden character: \" \" or a \"_\"")
    treatedId=sanitizeLayerId(svgLayerId)
    #If the start of the layer id is the target id, then yes, it's the layer we're looking for (or a lookalike)
    return treatedId==target
#endregion

def toggle_visibility_of_children_recursively(node, visibility):
    for child in node:
        toggle_svg_layer_visibility(child, visibility)

def toggle_visibility_of_parent_and_self_recursively(node, visibility):
    toggle_svg_layer_visibility(node, visibility)
    if(node.find("..")!=None):
        toggle_visibility_of_parent_and_self_recursively(node.find(".."),visibility)

generatedSvgsCounter=0
#Since PHotoshop is bad at handling text (no complex unicode symbols because there's no fallback font system), we use the template of preview, but just export a single text layer at a time to insert it in lieu of 
#photoshop's text layer, it will bump up the time of render to all hell though
def exportSingleTextLayerWithNewContent(layerPath:str, textContent:str, newFontSize:int=None):
    global generatedSvgsCounter
    generatedSvgsCounter+=1

    svgTemplatePath=os.path.join(os.getcwd(),settings["TemplateSvgFile"])
    parser1 = ET.XMLParser(encoding="utf-8")
    tree = ET.parse(svgTemplatePath,parser1)
    root = tree.getroot()
    #Font size between photoshop and svg are not the same, but min and max font size in the settings are expressed for photoshop, so we get the ratio that was calculated when we processed the svg template with process_template.py
    fontScaleRatio=float(tree.getroot().attrib["fontScaleRatio"])
    psdToSvgCoordinatesMultiplier=float(tree.getroot().attrib["psdToSvgCoordinatesMultiplier"])
    
    childCount=0
    for child in root:
        childCount+=1
        toggle_visibility_of_children_recursively(child, False)

    chosenOne=get_svg_layer_by_path(root,layerPath)
    toggle_visibility_of_parent_and_self_recursively(chosenOne, True)
    change_text_of_svg_layer(chosenOne, textContent)
    if(newFontSize!=None): 
        change_font_size_of_svg_layer(chosenOne,newFontSize,fontScaleRatio,psdToSvgCoordinatesMultiplier)

    output = BytesIO()
    tree.write(output, encoding='utf-8', xml_declaration=True) 
    fileName=str(generatedSvgsCounter)
    generatedSvgPath=os.path.join(os.getcwd(),tempFolder,fileName+settings["GeneratedSvgsExtension"])
    with open(generatedSvgPath, "wb") as f:
        f.write(output.getbuffer())
    
    #temp directory aren't liked by photoshop, so we save it in the working directory, in a temp folder ignored by git
    if(os.path.exists(tempFolder)==False): os.mkdir(tempFolder)
    exportPath = os.path.join(tempFolder,str(fileName)+".png")
    #inkScape is the only software that respects our svg, so we'll just run it
    inkscapeCommand="inkscape \""+os.path.relpath(generatedSvgPath, os.getcwd())+"\" --export-filename=\""+os.path.relpath(exportPath, os.getcwd())+"\" --export-dpi="+str(settings["PreviewDPI"])
    #print(inkscapeCommand)
    os.system(inkscapeCommand)
    time.sleep(1)
    return exportPath

#region Photoshop management
#Get layer by path written as Group/Group/Layer, for exampel Infos/Name
def get_layer_by_path(ps, layerPath):
    subGroups=str(layerPath).split("/")
    if(len(subGroups)<=1):
        return ps.active_document.artLayers.getByName(layerPath)
    
    i=0
    layerGroup=ps.active_document
    while(i<len(subGroups)-1):
        layerGroup= layerGroup.layerSets.getByName(subGroups[i])
        i+=1

    return layerGroup.artLayers.getByName(subGroups[len(subGroups)-1])

#https://loonghao.github.io/photoshop-python-api/examples/#replace-images
def replace_image(ps, layerToReplace, input_file):
    active_layer = layerToReplace
    ps.active_document.activeLayer=active_layer
    bounds = active_layer.bounds
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, input_file)
    ps.app.executeAction(replace_contents, desc)

    # replaced image.
    current_bounds = active_layer.bounds
    width = bounds[2] - bounds[0]
    height = bounds[3] - bounds[1]

    current_width = current_bounds[2] - current_bounds[0]
    current_height = current_bounds[3] - current_bounds[1]
    sizeMultiplier=width / current_width   
    newHeight=sizeMultiplier*current_height
    if(newHeight<height):
        sizeMultiplier=height/current_height

    new_size = sizeMultiplier * 100
    active_layer.resize(new_size, new_size, ps.AnchorPosition.MiddleCenter)

#https://graphicdesign.stackexchange.com/a/165157
def ptToPx(pt:float):
    return (settings["PreviewDPI"]/72) * pt

def pxToPt(px:float):
    return (72/settings["PreviewDPI"]) * px

def replace_psd_text_layer(ps, layerPath, layer, newText, replaceTextsWithSvgExports=True,fontSizeInPx:int=None):
    if(replaceTextsWithSvgExports==False):
        layer.textItem.contents = newText
        if(fontSizeInPx!=None):
            layer.font_size=pxToPt(fontSizeInPx)
        return
    pngPath=exportSingleTextLayerWithNewContent(layerPath,newText, fontSizeInPx)
    #We resize the png using pillow because trying to have inkscape or photoshop do it is a pain
    #I don't really know why but in this script os.system in export makes us wait until the file is created
    while(True):
        try:
            with Image.open(pngPath) as img:
                resized_img = img.resize((int(ps.active_document.width), int(ps.active_document.height)),Image.LANCZOS)
                resized_img.save(pngPath)
                break
        except:
            time.sleep(1)

    layer.textItem.contents=""
    desc = ps.ActionDescriptor
    ps.active_document.activeLayer=layer
    desc.putPath(ps.app.charIDToTypeID("null"), pngPath.replace("\\", "\\\\"))#"C:\\Users\\Utilisateur\\Documents\\GitHub\\Pokenjmin-Bot\\Template_Pokenjmin.png")
    event_id = ps.app.charIDToTypeID("Plc ")  # `Plc` need one space in here.
    ps.app.executeAction(ps.app.charIDToTypeID("Plc "), desc)
    newLayer=ps.active_document.activeLayer

#Very close to bot.py's create_svg_card 
def create_psd_card(cardDatas, cohort, spe, fileName, cardImagesName, isPreview=False, replaceTextsWithSvgExports=True):
    with Session(os.path.join(os.getcwd(),settings["TemplatePsdFile"]), action="open", auto_close=True) as ps:
        i=0

        previewWatermark=ps.active_document.layerSets.getByName(settings["PreviewLayerGroup"])
        previewWatermark.visible=isPreview
        
        ownerNameLayer = get_layer_by_path(ps,settings["OwnerNameLayer"])
        replace_psd_text_layer(ps,settings["OwnerNameLayer"],ownerNameLayer,cardDatas["owner_name"],replaceTextsWithSvgExports)

        cardNameLayer = get_layer_by_path(ps,settings["CardNameLayer"])
        replace_psd_text_layer(ps,settings["CardNameLayer"],cardNameLayer,cardDatas["card_name"],replaceTextsWithSvgExports,cardDatas["card_name_font_size"])

        descriptionLayer = get_layer_by_path(ps,settings["DescriptionLayer"])
        replace_psd_text_layer(ps,settings["DescriptionLayer"],descriptionLayer,cardDatas["card_description"],replaceTextsWithSvgExports)

        cpNameLayer = get_layer_by_path(ps,settings["CPNameLayer"])
        replace_psd_text_layer(ps,settings["CPNameLayer"],cpNameLayer, str(cardDatas["cp_name"]).upper(),replaceTextsWithSvgExports)

        cpValueLayer = get_layer_by_path(ps,settings["CPValueLayer"])
        replace_psd_text_layer(ps,settings["CPValueLayer"],cpValueLayer,str(cardDatas["cp_value"]),replaceTextsWithSvgExports)

        bottomTextLayer = get_layer_by_path(ps,settings["BottomTextLayer"])
        bottomTextContent= "["+cardDatas["bottom_text_title"]+"] "+cardDatas["bottom_text_content"]
        replace_psd_text_layer(ps,settings["BottomTextLayer"],bottomTextLayer,bottomTextContent,replaceTextsWithSvgExports)

        cardImagePath=os.path.join(os.getcwd(),settings["CardImagesFolder"],cardImagesName)
        if os.path.exists(cardImagePath):
            cardImageLayer=get_layer_by_path(ps,settings["CardImageLayer"])
            replace_image(ps,cardImageLayer,cardImagePath)

        ownerPhotoPath=os.path.join(os.getcwd(),settings["OwnerPhotosFolder"],cardImagesName)
        if os.path.exists(ownerPhotoPath):
            ownerPhotoLayer=get_layer_by_path(ps,settings["OwnerPhotoLayer"])
            replace_image(ps,ownerPhotoLayer,ownerPhotoPath)

        skill1Datas=cardDatas["skill1"]
        skill1LayerSet=ps.active_document.layerSets.getByName(settings["Skill1Group"])
        fill_layers_for_skill(ps,settings["Skill1Group"],skill1LayerSet,skill1Datas)

        skill2Datas=cardDatas["skill2"]
        skill2LayerSet=ps.active_document.layerSets.getByName(settings["Skill2Group"])
        fill_layers_for_skill(ps,settings["Skill2Group"],skill2LayerSet,skill2Datas)

        if(spe==None): spe=0

        speIconLayerGroup=ps.active_document.layerSets.getByName(settings["SpeIconGroupName"])
        set_spe_image(speIconLayerGroup,spe,"IconLayerName")

        backgroundLayerGroup=ps.active_document.layerSets.getByName(settings["BackgroundsGroupName"])
        set_spe_image(backgroundLayerGroup, spe,"BackgroundLayerName")

        watermarkLayerGroup=ps.active_document.layerSets.getByName(settings["WatermarkGroupName"])
        set_spe_image(watermarkLayerGroup, spe,"WatermarkLayerName")

        cohortNameLayer = get_layer_by_path(ps,settings["CohortNameValueLayer"])
        replace_psd_text_layer(ps,settings["CohortNameValueLayer"],cohortNameLayer,cohort,replaceTextsWithSvgExports)

        if isPreview:
            option = ps.JPEGSaveOptions()
            option.quality=1
            #you can't change the "jpg" part of the export path (for jpeg for example), Photoshop would overwrite it
            jpegPath = os.path.join(mkdtemp(),str(fileName)+".jpg")
            ps.active_document.saveAs(jpegPath, option)
            return jpegPath

        #export the pdf
        option = ps.PDFSaveOptions()
        option.jpegQuality = 12
        option.layers = False
        option.view = False  # opens the saved PDF in Acrobat.
        pdf = os.path.join(os.getcwd(),settings["ExportPdfFolder"],fileName+".pdf")
        ps.active_document.saveAs(pdf, option)
        return pdf

def fill_layers_for_skill(ps, skillLayerGroupPath, skillLayerGroup, skillDatas):
    skillDescLayerPath=skillLayerGroupPath+"/"+settings["SkillDescLayerName"]
    skillDescLayer=get_layer_by_path(ps,skillDescLayerPath)
    replace_psd_text_layer(ps,skillDescLayerPath,skillDescLayer,str(skillDatas["skill_desc"]))

    skillTitleLayerPath=skillLayerGroupPath+"/"+settings["SkillTitleLayerName"]
    skillTitleLayer=get_layer_by_path(ps,skillTitleLayerPath)
    replace_psd_text_layer(ps,skillTitleLayerPath,skillTitleLayer,str(skillDatas["skill_name"]))

    skillCostLayerPath=skillLayerGroupPath+"/"+settings["SkillCostLayerName"]
    skillCostLayer=get_layer_by_path(ps,skillCostLayerPath)
    skillCost=skillDatas["skill_cost"]
    if(skillCost<-9999999):
        skillCost=""
    skillCostLayer.textItem.contents=str(skillCost)
    replace_psd_text_layer(ps,skillCostLayerPath,skillCostLayer,str(skillCost))

    spe1IconGroup=skillLayerGroup.layerSets.getByName(settings["Spe1IconGroupName"])
    set_spe_image(spe1IconGroup,skillDatas["spe1"],"IconLayerName")

    spe2IconGroup=skillLayerGroup.layerSets.getByName(settings["Spe2IconGroupName"])
    set_spe_image(spe2IconGroup,skillDatas["spe2"],"IconLayerName")

    spe3IconGroup=skillLayerGroup.layerSets.getByName(settings["Spe3IconGroupName"])
    set_spe_image(spe3IconGroup,skillDatas["spe3"],"IconLayerName")

    return

def set_spe_image(speIconsGroup, speId, imageLayerKey):
    chosenSpe=None
    for spe in settings["Specialties"]:
        if spe["Id"]==speId:
            chosenSpe=spe
            break
    
    if(chosenSpe==None):
        speIconsGroup.visible=False
        return

    for iconLayer in speIconsGroup.artLayers:
        iconLayer.visible=iconLayer.name==chosenSpe[imageLayerKey]
#endregion

if(len(sys.argv)<2):
    print("/!\\ You need to pass a json with card datas as input, generate it with the command /export_all on the bot")
    exit(0)

inputPath=sys.argv[1]
if(inputPath==None):
    print("/!\\ You need to pass a json with card datas as input, generate it with the command /export_all on the bot")
    exit(0)
if(os.path.exists(inputPath)==False):
    print("/!\\ Path to json doesnt exist")
    exit(0)

with open(inputPath, encoding='utf-8') as fh:
    users = json.load(fh)

i=0
nbrOfUsers=len(users)
merger = PdfWriter()
for user in users:
    i+=1
    card=user["card"]
    print("Card "+str(i)+"/"+str(nbrOfUsers)+" - Owner:"+card["owner_name"]+" - Card name:"+card["card_name"])
    start=time.perf_counter()
    pngImagesName=str(user["discord_id"])+".png"
    fileName=(str(user["cohort"])+"-"+str(user["spe"])+"-"+str(i))+".generated"
    merger.append(create_psd_card(card,user["cohort"],user["spe"],fileName,pngImagesName,False))
    end=time.perf_counter()
    print("\tFinished in "+str(end-start)+"s")

merger.write(os.path.join(settings["ExportPdfFolder"],"0-FullDeck.generated.pdf"))
merger.close
shutil.rmtree(tempFolder)